version: "3.8"
networks:
  app-network:
    driver: bridge
services:
  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
      dockerfile: nginx.dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
    depends_on:
      - php
      - mysql
      - composer
      - npm
    networks:
      - app-network
  php:
    container_name: php
    build:
      context: ./docker/php
      dockerfile: php.dockerfile
    networks:
      - app-network
    working_dir: /var/www
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www
  composer:
    container_name: composer
    build:
      context: ./docker/composer
      dockerfile: composer.dockerfile
    networks:
      - app-network
    volumes:
      - ./src:/var/www
  mysql:
    image: mysql:8.0.27
    container_name: mysql
    tty: true
    networks:
      - app-network
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '$$Uu946!'
      MYSQL_DATABASE: laravel_crud_example
      MYSQL_USER: admin
      MYSQL_PASSWORD: 'jksjhd7cmds4#'
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql
  npm:
    container_name: npm
    build:
      context: ./docker/npm
      dockerfile: npm.dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    networks:
      - app-network
    volumes:
      - ./src:/var/www
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    restart: on-failure
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - app-network
  redis:
    image: redis:6.2.1-buster
    container_name: redis
    restart: unless-stopped
    expose:
      - 6379
    tty: true
    volumes:
      - ./database/redis/data:/data
    networks:
      - app-network